language: zh-CN

disable_top_img: true
index_img: https://howiechen95.com/group1/M00/00/00/CgAMB2DZ-3mAP7IEAANUbLBmHuA681.jpg
#index_img: https://howiechen95.com/group1/M00/00/00/CgAMB2DZ-3yANMmkAAFzMLwulHs002.jpg

archive_img: https://howiechen95.com/group1/M00/00/00/CgAMB2DbUXeACiLqAAK0fQnxMbI099.jpg

# Avatar (頭像)
avatar:
  img: https://howiechen95.com/group1/M00/00/00/CgAMB2DtsGeAQ9tOAAFfbRxs-WA526.jpg
  effect: false

footer:
  owner:
    enable: true
    since: 2021
  custom_text: <div class="icp"><a href="http://beian.miit.gov.cn" target="_blank" rel="noopener"><img class="icp-icon entered loading" src="/img/icp.png" data-ll-status="loading"><span>粤ICP备2021092723号</span></a></div>
  copyright: true # Copyright of theme and framework

cover:
  # 是否顯示文章封面
  index_enable: true
  aside_enable: true
  archives_enable: true
  # 封面顯示的位置
  # 三個值可配置 left , right , both
  position: both
  # 當沒有設置cover時，默認的封面顯示
#  default_cover:
#  - https://cdn.jsdelivr.net/gh/jerryc127/CDN@latest/cover/default_bg.png
menu:
  首页: / || fas fa-home
  目录 ||fa-fw fas fa-compass:
    归档: /archives/ || fas fa-archive
    标签: /tags/ || fas fa-tags
    分类: /categories/ || fas fa-folder-open
  生活 || fa fa-heartbeat:
    书单: /library/ || fa-fw fas fa-book
    音乐: /music/ || fas fa-music
    照片: /gallery/ || fas fa-images
    电影: /movies/ || fas fa-video
  孤岛 || fa-fw fas fa-cubes :
    工具: /tools/ || fas fa-toolbox
    一个想法: /think/ || fa-fw fas fa-comment-dots
    TODO: /todo/ || far fa-check-circle
#  友链: /link/ || fas fa-link
  关于: /about/ || fas fa-mask

aside:
  enable: true
  hide: false
  button: true
  mobile: true # display on mobile
  position: right # left or right
  card_author:
    enable: true
    description:
    button:
      enable: true
      icon: fab fa-github
      text: Follow Me
      link: https://github.com/howiechen95
  card_announcement:
    enable: true
    content: 在学了，别催！！
  card_recent_post:
    enable: true
    limit: 5 # if set 0 will show all
    sort: date # date or updated
    sort_order: # Don't modify the setting unless you know how it works
  card_categories:
    enable: true
    limit: 8 # if set 0 will show all
    expand: none # none/true/false
    sort_order: # Don't modify the setting unless you know how it works
  card_tags:
    enable: true
    limit: 40 # if set 0 will show all
    color: true
    sort_order: # Don't modify the setting unless you know how it works
  card_archives:
    enable: true
    type: monthly # yearly or monthly
    format: MMMM YYYY # eg: YYYY年MM月
    order: -1 # Sort of order. 1, asc for ascending; -1, desc for descending
    limit: 8 # if set 0 will show all
    sort_order: # Don't modify the setting unless you know how it works
  card_webinfo:
    enable: true
    post_count: true
    last_push_date: false
    sort_order: # Don't modify the setting unless you know how it works

highlight_theme: mac #  darker / pale night / light / ocean / mac / mac light / false
highlight_copy: true # copy button
highlight_lang: false # show the code language
highlight_shrink: false # true: shrink the code blocks / false: expand the code blocks | none: expand code blocks and hide the button
highlight_height_limit: false # unit: px
code_word_wrap: false


# canvas_ribbon (靜止彩帶背景)
# See: https://github.com/hustcc/ribbon.js
canvas_ribbon:
  enable: false
  size: 150
  alpha: 0.6
  zIndex: -1
  click_to_change: true
  mobile: false

# Fluttering Ribbon (動態彩帶)
canvas_fluttering_ribbon:
  enable: false
  mobile: false

# canvas_nest
# https://github.com/hustcc/canvas-nest.js
canvas_nest:
  enable: false
  color: '0,0,255' #color of lines, default: '0,0,0'; RGB values: (R,G,B).(note: use ',' to separate.)
  opacity: 0.7 # the opacity of line (0~1), default: 0.5.
  zIndex: -1 # z-index property of the background, default: -1.
  count: 99 # the number of lines, default: 99.
  mobile: false

# Mouse click effects: fireworks (鼠標點擊效果: 煙火特效)
fireworks:
  enable: false
  zIndex: 9999 # -1 or 9999
  mobile: false

activate_power_mode:
  enable: false
  colorful: true # open particle animation (冒光特效)
  shake: true #  open shake (抖動特效)
  mobile: false

# Mouse click effects: words (鼠標點擊效果: 文字)
ClickShowText:
  enable: false
  text:
   - 富强
   - 民主
   - 文明
   - 和谐
   - 自由
   - 平等
   - 公正
   - 法治
   - 爱国
   - 敬业
   - 诚信
   - 友善
  fontSize: 15px
  random: false
  mobile: true

#preloader: true


# Time difference between publish date and now (網頁運行時間)
# Formal: Month/Day/Year Time or Year/Month/Day Time
runtimeshow:
  enable: true
  publish_date: 06/25/2021

# Change font size
change_font_size: false

# Conversion between Traditional and Simplified Chinese (簡繁轉換)
translate:
  enable: true
  # The text of a button
  default: 簡
  # the language of website (1 - Traditional Chinese/ 2 - Simplified Chinese）
  defaultEncoding: 1
  # Time delay
  translateDelay: 0
  # The text of the button when the language is Simplified Chinese
  msgToTraditionalChinese: '繁'
  # The text of the button when the language is Traditional Chinese
  msgToSimplifiedChinese: '簡'

# Snackbar 彈窗
# https://github.com/polonel/SnackBar
# position 彈窗位置
# 可選 top-left / top-center / top-right / bottom-left / bottom-center / bottom-right
#snackbar:
#  enable: true
#  position: bottom-left
#  bg_light: '#49b1f5' #light mode時彈窗背景
#  bg_dark: '#2d3035' #dark mode時彈窗背景
#
#pangu:
#  enable: true
#  field: post # site/post

#live2d:
#  enable: true    # 是否启用看板娘
#  scriptFrom: local    # 默认
#  pluginRootPath: live2dw/    # 插件在站点上的根目录(相对路径)
#  pluginJsPath: lib/    # 脚本文件相对与插件根目录路径
#  pluginModelPath: assets/    # 模型文件相对与插件根目录路径
#  # scriptFrom: jsdelivr    # jsdelivr CDN
#  # scriptFrom: unpkg    # unpkg CDN
#  # scriptFrom: https://cdn.jsdelivr.net/npm/live2d-widget@3.x/lib/L2Dwidget.min.js    # 你的自定义 url
#  tagMode: false # 标签模式, 是否仅替换 live2d tag标签而非插入到所有页面中
#  debug: false # 调试, 是否在控制台输出日志
#  model:
#    use: live2d-widget-model-hibiki # npm-module 包的名字
#    scale: 1
#    hHeadPos: 0.5
#    vHeadPos: 0.618
#  display:
#    superSample: 2
#    width: 200
#    height: 400
#    position: left    # 左侧还是右侧
#    hOffset: -30
#    vOffset: -20    # 距底部距离
#  mobile:
#    show: false    # 手机端是否可见，建议不可见否则可能影响阅读
#    scale: 0.5
#  react:
#    opacityDefault: 0.7
#    opacityOnHover: 0.2

live2d:
  enable: false
  scriptFrom: local
  pluginRootPath: live2dw/
  pluginJsPath: lib/
  pluginModelPath: assets/
  tagMode: false
  debug: false
  model:
    use: live2d-widget-model-hibiki
  display:
    position: right
    width: 100
    height: 200
  mobile:
    show: false